# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_house.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11smart_house.proto\"%\n\x15RequestIdentification\x12\x0c\n\x04msgn\x18\x01 \x01(\t\"4\n\nDeviceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\")\n\x12TemperatureReading\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"\x1c\n\x0bLampControl\x12\r\n\x05is_on\x18\x01 \x01(\x08\"\x1c\n\tTvChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\"\x9a\x03\n\x0eGatewayMessage\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.GatewayMessage.MessageType\x12\"\n\x0b\x64\x65vice_info\x18\x02 \x01(\x0b\x32\x0b.DeviceInfoH\x00\x12+\n\x0ctemp_reading\x18\x03 \x01(\x0b\x32\x13.TemperatureReadingH\x00\x12$\n\x0clamp_control\x18\x04 \x01(\x0b\x32\x0c.LampControlH\x00\x12 \n\ntv_channel\x18\x05 \x01(\x0b\x32\n.TvChannelH\x00\x12\x38\n\x16request_identification\x18\x06 \x01(\x0b\x32\x16.RequestIdentificationH\x00\"\x7f\n\x0bMessageType\x12\x19\n\x15\x44\x45VICE_IDENTIFICATION\x10\x00\x12\x17\n\x13TEMPERATURE_READING\x10\x01\x12\x10\n\x0cLAMP_CONTROL\x10\x02\x12\x0e\n\nTV_CHANNEL\x10\x03\x12\x1a\n\x16REQUEST_IDENTIFICATION\x10\x04\x42\t\n\x07messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_house_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTIDENTIFICATION']._serialized_start=21
  _globals['_REQUESTIDENTIFICATION']._serialized_end=58
  _globals['_DEVICEINFO']._serialized_start=60
  _globals['_DEVICEINFO']._serialized_end=112
  _globals['_TEMPERATUREREADING']._serialized_start=114
  _globals['_TEMPERATUREREADING']._serialized_end=155
  _globals['_LAMPCONTROL']._serialized_start=157
  _globals['_LAMPCONTROL']._serialized_end=185
  _globals['_TVCHANNEL']._serialized_start=187
  _globals['_TVCHANNEL']._serialized_end=215
  _globals['_GATEWAYMESSAGE']._serialized_start=218
  _globals['_GATEWAYMESSAGE']._serialized_end=628
  _globals['_GATEWAYMESSAGE_MESSAGETYPE']._serialized_start=490
  _globals['_GATEWAYMESSAGE_MESSAGETYPE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
